name: Test workflow

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TOKEN: ${{ secrets.TOKEN }}
  
jobs:

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |-
          echo "${{ github.head_ref || github.ref_name }}"

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: Download Logs
        if: ${{ always() }}
        shell: bash
        run: |
          mkdir logs
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            https://api.github.com/repos/${{github.repository}}/actions/runs/${{github.run_number}}/logs --output-dir ./logs

      - name: Upload Test Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          # Produced by getJarvisDiag.sh
          path: ./logs
          if-no-files-found: ignore
